In [2]:
# autogradによる自動微分
import autograd
import autograd.numpy as np

def loss(w, x):
    return -np.log(1.0 / (1.0 + np.exp(-np.dot(w, x))))

x = np.array([1.0, 1.0, 1.0])
w = np.array([1.0, 1.0, -1.5])

grad_loss = autograd.grad(loss)
print(loss(w, x))
print(grad_loss(w, x))

0.47407698418010663
[-0.37754067 -0.37754067 -0.37754067]


In [9]:
# tensorflowによる自動微分
import tensorflow as tf

dtype = tf.float32

x = tf.constant([1, 1, 1], dtype = dtype, name = 'x')
w = tf.Variable([1.0, 1.0, -1.5], dtype = dtype, name = 'w')

with tf.GradientTape() as tape:
    loss = -tf.math.log(tf.math.sigmoid(tf.tensordot(x, w, 1)))
print(loss.numpy())
print(tape.gradient(loss, w))

0.47407696
tf.Tensor([-0.37754062 -0.37754062 -0.37754062], shape=(3,), dtype=float32)


In [16]:
# pytorchによる自動微分
import torch

dtype = torch.float

x = torch.tensor([1, 1, 1], dtype = dtype)
w = torch.tensor([1.0, 1.0, -1.5], dtype = dtype, requires_grad = True)

loss = -torch.dot(x, w).sigmoid().log()
loss.backward()
print(loss.item())
print(w.grad)

0.4740769565105438
tensor([-0.3775, -0.3775, -0.3775])
