In [1]:
# Activation function:Step function
import numpy as np

x = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
y = np.array([0, 1, 1, 1])
w = np.array([0.0, 0.0, 0.0])

eta = 1.0

for t in range(100):
    for i in range(len(y)):
        y_pred = np.heaviside(np.dot(x[i], w), 0)
        w += (y[i] - y_pred) * eta * x[i]
        
display(w)
display(np.heaviside(np.dot(x, w), 0))

array([1., 1., 0.])

array([0., 1., 1., 1.])

In [3]:
# SGD
# Activation function:Sigmoid function
import numpy as np

def sigmoid(v):
    return 1.0 / (1 + np.exp(-v))

x = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
y = np.array([0, 1, 1, 1])
w = np.array([0.0, 0.0, 0.0])

eta = 1.0

for t in range(100):
        y_pred = sigmoid(np.dot(x, w))
        w += eta * np.dot((y - y_pred), x)
        
display(w)
display(np.heaviside(np.dot(x, w), 0))

array([ 6.80884081,  6.80884081, -2.92825318])

array([0., 1., 1., 1.])